services:
  # Nginx reverse proxy to simulate your setup
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx-test.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - aircraft-goaround
    networks:
      - proxy-network

  aircraft-goaround:
    image: aircraft-goaround:dev
    environment:
      - TAR1090_URL=http://tar1090:80
      - WEB_PORT=8889
      - ENABLE_WEB=true
    volumes:
      - /tmp/aircraft-goaround-data:/app/data
    expose:
      - "8889"
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge