#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2015,SC2016

source /scripts/common

# Start Go-Around Tracker
# shellcheck disable=SC2086
exec python3 /app/go_around_tracker.py \
    --server "${TAR1090_URL}" \
    --web \
    --web-port 8889 \
    --interval "${UPDATE_INTERVAL:-5}"