name: Docker Compose Lint

permissions:
  contents: read

on:
  pull_request:
    paths:
      - "docker-compose*.yml"
      - ".github/workflows/docker-compose-lint.yml"
  push:
    branches:
      - main
      - master
    paths:
      - "docker-compose*.yml"
      - ".github/workflows/docker-compose-lint.yml"

jobs:
  validate:
    name: Validate Docker Compose files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate docker-compose.yml
        run: docker compose -f docker-compose.yml config --quiet

      - name: Validate docker-compose.proxy-test.yml
        run: docker compose -f docker-compose.proxy-test.yml config --quiet
        if: hashFiles('docker-compose.proxy-test.yml') != ''

      - name: Check for secrets in compose files
        run: |
          # Check for potential secrets or sensitive data
          for file in docker-compose*.yml; do
            if [ -f "$file" ]; then
              echo "Checking $file for potential secrets..."
              if grep -iE "(password|secret|token|key|api).*[:=].*['\"]" "$file"; then
                echo "Warning: Potential secrets found in $file"
              fi
            fi
          done