name: ShellCheck

on:
  pull_request:
    paths:
      - "**.sh"
      - "rootfs/**"
      - ".github/workflows/shellcheck.yml"
  push:
    branches:
      - main
      - master
    paths:
      - "**.sh"
      - "rootfs/**"
      - ".github/workflows/shellcheck.yml"

permissions:
  contents: read

jobs:
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: "./rootfs"
          severity: warning